stages:
  - build
  - deploy

default:
  tags:
    - develop

services:
  - docker:19.03.13-dind

build-job:
  stage: build
  tags:
    - develop
  script:
    - echo "Compiling the code..."
    - echo "build"
    - docker build -t mobile-app .
  only:
    - develop

deploy-job:
  stage: deploy
  tags:
    - develop
  script:
    - echo "Start webpack ..."
    - docker-compose -f ./app.yml up -d
  only:
    - develop

deploy-qa:
  stage: deploy
  script:
    - echo "[QA]running build start"
    - docker build -t qa-mobile-app .
    - echo "[QA] deploy start"
    - docker-compose -f ./app-qa.yml up -d
    - echo "[QA]deploy ended"
  tags:
    - qa
  only:
    - develop-qa
