stages:
  - build
  - deploy

variables:
  MAJOR_VERSION: '1'
  MINOR_VERSION: '0'
  PATCH_VERSION: '0'
  IMAGE_TAG: '$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION'

default:
  tags: # default tag for gitlab runner in verda stg env.
    - develop
services:
  - docker:24.0.9-dind

build-job:
  stage: build
  tags:
    - develop
  script:
    - echo "Compiling the code..."
    - echo "build"
    - docker build -t random-mobile:latest -f $CI_PROJECT_DIR/apps/mobile-app/Dockerfile .
  only:
    - master

deploy-job:
  stage: deploy
  tags:
    - develop
  script:
    - echo "Start deploy ..."
    - cd $CI_PROJECT_DIR/apps/mobile-app
    - docker-compose -f ./app.yml up -d
  only:
    - master
