version: '3'

services:
  mobile-app:
    image: random-mobile:latest
    container_name: random-mobile-app
    ports:
      - '3002:3002'
    environment:
      - KAKAO_RESTAPI_KEY=${KAKAO_RESTAPI_KEY}
      - KAKAO_JAVASCRIPT_KEY=${KAKAO_JAVASCRIPT_KEY}
      - TZ=Asia/Seoul
