stages:
  - build
  - deploy

variables:
  MAJOR_VERSION: '1'
  MINOR_VERSION: '0'
  PATCH_VERSION: '0'
  IMAGE_TAG: '$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION'

default:
  tags: # default tag for gitlab runner in verda stg env.
    - develop
services:
  - docker:24.0.9-dind

build-job:
  stage: build
  tags:
    - develop
  script:
    - echo "Compiling the code..."
    - echo "build"
    # Increase the PATCH_VERSION by 1 for every build
    - export PATCH_VERSION=$(($CI_PIPELINE_IID % 1000)) # Use the pipeline ID as the patch version
    # Update the IMAGE_TAG with the new PATCH_VERSION
    - export IMAGE_TAG="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
    # Tagging the Docker image with the updated version
    - docker build -t back:$IMAGE_TAG -f $CI_PROJECT_DIR/packages/back/Dockerfile .
  only:
    - master

deploy-job:
  stage: deploy
  tags:
    - develop
  script:
    - echo "Start deploy ..."
    - cd $CI_PROJECT_DIR/packages/back
    - docker-compose -f ./app.yml up -d
  only:
    - master
