stages:
  - build
  - deploy
default:
  tags:
    - develop
services:
  - docker:24.0.9-dind

build-job:
  stage: build
  tags:
    - develop
  script:
    - echo "Compiling the code..."
    - echo "build"
    - export PATCH_VERSION=1
    - docker build -t back:1.0.0 -f $CI_PROJECT_DIR/packages/back/Dockerfile .
  only:
    - master

deploy-job:
  stage: deploy
  tags:
    - develop
  script:
    - echo "Start deploy ..."
    - cd $CI_PROJECT_DIR/packages/back
    - docker-compose -f ./app.yml up -d
  only:
    - master
