stages:
  - build
  - deploy
default:
  tags:
    - develop
services:
  - docker:24.0.9-dind
# test 구라면 주거ㄴㄴㅇㄴㄴ
build-job:
  stage: build
  tags:
    - develop
  script:
    - echo "Compiling the code..."
    - echo "build"
    - docker build --rm -t back:latest -f $CI_PROJECT_DIR/packages/back/Dockerfile .
  after_script:
    - docker rmi $(docker images -f "dangling=true" -q) || true
  only:
    - master

deploy-job:
  stage: deploy
  tags:
    - develop
  script:
    - echo "Start deploy ..."
    - cd $CI_PROJECT_DIR/packages/back
    - docker-compose -f ./app.yml up -d
  only:
    - master
