version: '3'

services:
  backend:
    image: backend
    ports:
      - '3000:3000'
    environment:
      - KAKAO_RESTAPI_KEY=${KAKAO_RESTAPI_KEY}
      - TYPEORM_URL=${TYPEORM_URL}
      - TZ=Asia/Seoul
    depends_on:
      - db

  db:
    image: postgres:12.18-bullseye
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
