version: '3'

services:
  backend:
    image: back:latest
    container_name: random-picker-backend
    ports:
      - '3000:3000'
    environment:
      - KAKAO_RESTAPI_KEY=${KAKAO_RESTAPI_KEY}
      - TYPEORM_URL=${TYPEORM_URL}
      - TZ=Asia/Seoul
    depends_on:
      - db

  db:
    image: postgres:12.18-bullseye
    ports:
      - '5434:5432' # 5432 포트가 이미 사용중이라 5434로 변경
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
