name: MonoRepo CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # 프론트엔드 빌드 및 테스트
      - name: Build and Test Frontend
        run: |
          cd packages/front
          npm install
          npm run build

      # 백엔드 빌드 및 테스트
      - name: Build and Test Backend
        run: |
          cd packages/back
          npm install
          npm run build

      # 이후 추가적인 작업 수행 가능
